"use client";
import { useEffect, useState } from 'react';
import { apiRequest, authenticatedFetch } from './api-client';
import { Dialog } from './receiving-ui';
import type { SessionUser, Shipment } from './types';
export function AccountActivation({user,token,onUpdate,onLogout}:{user:SessionUser;token:string;onUpdate:(user:SessionUser)=>void;onLogout:()=>void}) {
  const [code,setCode]=useState(''),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const run=async(path:string,body:unknown)=>{setBusy(true);setMessage('');try{return await apiRequest<{user?:SessionUser}>(token,path,'POST',body);}catch(error){setMessage(error instanceof Error?error.message:'Unable to complete this step');return null;}finally{setBusy(false);}};
  return <div className="activation-screen"><section className="activation-card"><span className="eyebrow">Welcome to DockFlow</span><h1>Activate your account</h1><p>{user.name} · {user.email}</p><ol className="activation-steps"><li className={user.emailVerifiedAt?'done':''}>Verify email</li><li className={!user.mustChangePassword?'done':''}>Set your password</li></ol>{!user.emailVerifiedAt?<form onSubmit={async event=>{event.preventDefault();const result=await run(`/api/users/${user.id}/email/verify`,{code});if(result?.user)onUpdate(result.user);}}><p>A six-digit verification code is sent when the account is created.</p><label>Verification code<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={event=>setCode(event.target.value)} required/></label><div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={async()=>{if(await run(`/api/users/${user.id}/email/send-code`,{}))setMessage('A new code was sent to your email.');}}>Resend code</button><button className="button primary" disabled={busy}>Verify email</button></div></form>:<form onSubmit={async event=>{event.preventDefault();if(newPassword!==confirm){setMessage('The new passwords do not match.');return;}if(await run('/api/auth/change-password',{currentPassword,newPassword}))onLogout();}}><label>Initial / current password<input type="password" autoComplete="current-password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)} required/></label><label>New password<input type="password" autoComplete="new-password" minLength={8} value={newPassword} onChange={event=>setNewPassword(event.target.value)} required/></label><label>Confirm new password<input type="password" autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)} required/></label><button className="button primary" disabled={busy}>Save password & sign in again</button></form>}{message&&<p role="status" className="form-error">{message}</p>}<button className="text-button" onClick={onLogout}>Sign out</button></section></div>;
}
type EmailPlan={schedule:{day:number;time:string};nextSendAt:string;configured:boolean;accounts:{id:number;name:string;email:string;verified:boolean;lastSentAt:string|null}[]};
export function EmailSchedule({token}:{token:string}) {
  const [plan,setPlan]=useState<EmailPlan|null>(null),[day,setDay]=useState(1),[time,setTime]=useState('09:00'),[message,setMessage]=useState('');
  useEffect(()=>{apiRequest<EmailPlan>(token,'/api/admin/email-schedule','GET').then(plan=>{setPlan(plan);setDay(plan.schedule.day);setTime(plan.schedule.time);}).catch(error=>setMessage(error.message));},[token]);
  const when=(date:string)=>new Intl.DateTimeFormat('en-PH',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Manila'}).format(new Date(date));
  return <details className="panel email-schedule"><summary><b>Monthly performance emails</b><span>{plan?`Next: ${when(plan.nextSendAt)}`:'Loading schedule…'}</span></summary><form className="email-schedule-controls" onSubmit={async event=>{event.preventDefault();try{const result=await apiRequest<{nextSendAt:string}>(token,'/api/admin/email-schedule','PUT',{day,time});setPlan(plan?{...plan,nextSendAt:result.nextSendAt,schedule:{day,time}}:null);setMessage('Email schedule saved.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to save');}}}><label>Day each month<select value={day} onChange={event=>setDay(Number(event.target.value))}>{Array.from({length:28},(_,i)=><option value={i+1} key={i}>{i+1}</option>)}</select></label><label>Manila time<input type="time" value={time} onChange={event=>setTime(event.target.value)} required/></label><button className="button primary">Save schedule</button></form><p>{plan?.configured?'Verified recipients receive the previous month’s performance.':'SMTP is not configured; scheduled emails cannot be sent yet.'}</p>{message&&<p role="status">{message}</p>}<div className="email-account-status">{plan?.accounts.map(account=><div key={account.id}><b>{account.name}</b><span>{account.verified?'Verified':'Email verification pending'}</span><small>{account.lastSentAt?`Last sent ${when(account.lastSentAt)}`:'No monthly email sent yet'}</small></div>)}</div></details>;
}
type ClearanceRecord={itemId:number;[key:string]:string|number};
export function ClearanceModal({shipment,token,onClose}:{shipment:Shipment;token:string;onClose:()=>void}) {
  const [records,setRecords]=useState<ClearanceRecord[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{apiRequest<{records:ClearanceRecord[]}>(token,`/api/shipments/${shipment.id}/clearance`,'GET').then(result=>setRecords(result.records)).catch(error=>setMessage(error.message));},[token,shipment.id]);
  const fields=[['materialType','PM / RM'],['helperCount','Number of helpers'],['truckType','Type of truck'],['palletCount','Number of pallets'],['actualReceived','Actual received'],['actualUom','Actual UOM'],['remarks','Non-compliance remarks'],['qaSample','QA sample (optional)'],['vacuum','Vacuum inspection'],['qaStart','QA start (optional)'],['qaEnd','QA end (optional)'],['clearedBy','Cleared by'],['receivingController','Receiving controller'],['inventoryController','Inventory controller']];
  const change=(id:number,key:string,value:string)=>setRecords(records.map(row=>row.itemId===id?{...row,[key]:value}:row));
  return <Dialog title="Inbound clearance" close={onClose}><form className="receiving-form clearance-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setMessage('');try{await apiRequest(token,`/api/shipments/${shipment.id}/clearance`,'PUT',{records});const response=await authenticatedFetch(`/api/shipments/${shipment.id}/clearance.pdf`,{},token);if(!response.ok)throw new Error('Clearance PDF could not be generated');const url=URL.createObjectURL(await response.blob());const anchor=document.createElement('a');anchor.href=url;anchor.download=`inbound-clearance-${shipment.shipmentNumber}.pdf`;anchor.click();URL.revokeObjectURL(url);}catch(error){setMessage(error instanceof Error?error.message:'Unable to download');}finally{setBusy(false);}}}><div className="clearance-copy-note"><b>PCL copy + Warehouse copy</b><span>The same values fill both halves. One page per material.</span></div>{records.map(row=><section className="clearance-material" key={row.itemId}><h3>{row.code} · {row.description}</h3><dl className="clearance-autofill"><div><dt>Supplier</dt><dd>{row.supplier}</dd></div><div><dt>Truck / driver</dt><dd>{row.truckPlate} · {row.driver}</dd></div><div><dt>DR / PO</dt><dd>{row.dr} / {row.po}</dd></div><div><dt>DR quantity</dt><dd>{row.quantity} {row.uom}</dd></div><div><dt>Supplier lot / SAP batch</dt><dd>{row.lot||'—'} / {row.batch||'—'}</dd></div><div><dt>Gate in</dt><dd>{row.arrival||'—'}</dd></div></dl><div className="form-grid"><label>Mode of delivery<select value={row.mode||''} onChange={event=>change(row.itemId,'mode',event.target.value)}><option value="">Not selected</option><option>PALLETIZED</option><option>MANUAL</option></select></label><label>Disposition<select value={row.disposition||''} onChange={event=>change(row.itemId,'disposition',event.target.value)}><option value="">Not selected</option><option>RELEASE</option><option>HOLD</option><option>REJECT</option></select></label>{fields.map(([key,label])=><label key={key}>{label}<input value={row[key]??''} onChange={event=>change(row.itemId,key,event.target.value)}/></label>)}</div></section>)}{message&&<p role="alert" className="form-error">{message}</p>}<div className="confirmation-footer"><small>Print on A4 landscape at actual size.</small><button className="button primary" disabled={busy||!records.length}>{busy?'Preparing…':'Save & download both copies'}</button></div></form></Dialog>;
}
