"use client";
import { useEffect, useState } from 'react';
import { Eye, EyeOff, LogOut } from 'lucide-react';
import { apiRequest, authenticatedFetch } from './api-client';
import { Dialog } from './receiving-ui';
import type { SessionUser, Shipment } from './types';
export function AccountActivation({user,token,onUpdate,onLogout}:{user:SessionUser;token:string;onUpdate:(user:SessionUser)=>void;onLogout:()=>void}) {
  const [code,setCode]=useState(''),[newPassword,setNewPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(user.verificationCodeSentAt?'A new code was sent to your email.':'');
  const [showNew,setShowNew]=useState(false),[showConfirm,setShowConfirm]=useState(false);
  const run=async(path:string,body:unknown)=>{setBusy(true);setMessage('');try{return await apiRequest<{user?:SessionUser}>(token,path,'POST',body);}catch(error){setMessage(error instanceof Error?error.message:'Unable to complete this step');return null;}finally{setBusy(false);}};
  const hideWhenFocusLeaves=(event:React.FocusEvent<HTMLSpanElement>,hide:()=>void)=>{if(!event.currentTarget.contains(event.relatedTarget as Node|null))hide();};
  return <div className="activation-screen"><section className="activation-card"><button className="activation-signout" onClick={onLogout}><LogOut size={16}/> Sign out</button><span className="eyebrow">Welcome to DockFlow</span><h1>Activate your account</h1><p>{user.name} · {user.email}</p>{!user.emailVerifiedAt?<form className="activation-form" onSubmit={async event=>{event.preventDefault();const result=await run(`/api/users/${user.id}/email/verify`,{code});if(result?.user)onUpdate(result.user);}}><label>Verification code<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,'').slice(0,6))} autoFocus required/></label><div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={async()=>{if(await run(`/api/users/${user.id}/email/send-code`,{}))setMessage('A new code was sent to your email.');}}>Resend code</button><button className="button primary" disabled={busy||code.length!==6}>Continue</button></div></form>:<form className="activation-form" onSubmit={async event=>{event.preventDefault();if(newPassword!==confirm){setMessage('The new passwords do not match.');return;}const result=await run('/api/auth/change-password',{newPassword});if(result?.user)onUpdate(result.user);}}><label>New password<span className="activation-password" onBlurCapture={event=>hideWhenFocusLeaves(event,()=>setShowNew(false))}><input type={showNew?'text':'password'} autoComplete="new-password" minLength={8} maxLength={100} value={newPassword} onChange={event=>setNewPassword(event.target.value)} required/><button type="button" onClick={()=>setShowNew(value=>!value)} aria-label={showNew?'Hide password':'Show password'}>{showNew?<EyeOff size={17}/>:<Eye size={17}/>}</button></span></label><label>Confirm new password<span className="activation-password" onBlurCapture={event=>hideWhenFocusLeaves(event,()=>setShowConfirm(false))}><input type={showConfirm?'text':'password'} autoComplete="new-password" minLength={8} maxLength={100} value={confirm} onChange={event=>setConfirm(event.target.value)} required/><button type="button" onClick={()=>setShowConfirm(value=>!value)} aria-label={showConfirm?'Hide password':'Show password'}>{showConfirm?<EyeOff size={17}/>:<Eye size={17}/>}</button></span></label><button className="button primary" disabled={busy||newPassword.length<8||newPassword!==confirm}>Save password</button></form>}{message&&<p role="status" className={message.startsWith('A new code')?'activation-message success':'activation-message error'}>{message}</p>}</section></div>;
}
type EmailAccount={id:number;name:string;email:string;verified:boolean;lastSentAt:string|null;enabled:boolean;day:number;time:string;nextSendAt:string};
type EmailPlan={configured:boolean;accounts:EmailAccount[]};
export function EmailSchedule({token}:{token:string}) {
  const [plan,setPlan]=useState<EmailPlan|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{apiRequest<EmailPlan>(token,'/api/admin/email-schedule','GET').then(setPlan).catch(error=>setMessage(error.message));},[token]);
  const when=(date:string)=>new Intl.DateTimeFormat('en-PH',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Manila'}).format(new Date(date));
  const change=(id:number,patch:Partial<EmailAccount>)=>setPlan(current=>current?{...current,accounts:current.accounts.map(account=>account.id===id?{...account,...patch}:account)}:current);
  return <details className="panel email-schedule"><summary><b>Monthly Performance</b><span>{plan?.configured?'Configured':'SMTP unavailable'}</span></summary><form onSubmit={async event=>{event.preventDefault();if(!plan||busy)return;setBusy(true);setMessage('');try{const result=await apiRequest<EmailPlan>(token,'/api/admin/email-schedule','PUT',{accounts:plan.accounts.map(({id,enabled,day,time})=>({id,enabled,day,time}))});setPlan(result);setMessage('Monthly performance settings saved.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to save');}finally{setBusy(false);}}}><div className="email-account-status">{plan?.accounts.map(account=><div key={account.id}><label className="email-enable"><input type="checkbox" checked={account.enabled} onChange={event=>change(account.id,{enabled:event.target.checked})}/><span><b>{account.name}</b><small>{account.email||'No email'}</small></span></label><label>Day<select value={account.day} disabled={!account.enabled} onChange={event=>change(account.id,{day:Number(event.target.value)})}>{Array.from({length:28},(_,i)=><option value={i+1} key={i}>{i+1}</option>)}</select></label><label>Time<input type="time" value={account.time} disabled={!account.enabled} onChange={event=>change(account.id,{time:event.target.value})}/></label><small>{account.enabled?`Next ${when(account.nextSendAt)}`:'Disabled'}{account.lastSentAt?` · Last ${when(account.lastSentAt)}`:''}</small></div>)}</div><div className="email-schedule-actions">{message&&<span role="status">{message}</span>}<button className="button primary" disabled={!plan||busy}>{busy?'Saving…':'Save settings'}</button></div></form></details>;
}
type ClearanceRecord={itemId:number;[key:string]:string|number};
export function ClearanceModal({shipment,token,onClose}:{shipment:Shipment;token:string;onClose:()=>void}) {
  const [records,setRecords]=useState<ClearanceRecord[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{apiRequest<{records:ClearanceRecord[]}>(token,`/api/shipments/${shipment.id}/clearance`,'GET').then(result=>setRecords(result.records)).catch(error=>setMessage(error.message));},[token,shipment.id]);
  const fields=[['materialType','PM / RM'],['helperCount','Number of helpers'],['truckType','Type of truck'],['palletCount','Number of pallets'],['actualReceived','Actual received'],['actualUom','Actual UOM'],['remarks','Non-compliance remarks'],['qaSample','QA sample (optional)'],['vacuum','Vacuum inspection'],['qaStart','QA start (optional)'],['qaEnd','QA end (optional)'],['clearedBy','Cleared by'],['receivingController','Receiving controller'],['inventoryController','Inventory controller']];
  const change=(id:number,key:string,value:string)=>setRecords(records.map(row=>row.itemId===id?{...row,[key]:value}:row));
  return <Dialog title="Inbound clearance" close={onClose}><form className="receiving-form clearance-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setMessage('');try{await apiRequest(token,`/api/shipments/${shipment.id}/clearance`,'PUT',{records});const response=await authenticatedFetch(`/api/shipments/${shipment.id}/clearance.pdf`,{},token);if(!response.ok)throw new Error('Clearance PDF could not be generated');const url=URL.createObjectURL(await response.blob());const anchor=document.createElement('a');anchor.href=url;anchor.download=`inbound-clearance-${shipment.shipmentNumber}.pdf`;anchor.click();URL.revokeObjectURL(url);}catch(error){setMessage(error instanceof Error?error.message:'Unable to download');}finally{setBusy(false);}}}><div className="clearance-copy-note"><b>PCL copy + Warehouse copy</b><span>The same values fill both halves. One page per material.</span></div>{records.map(row=><section className="clearance-material" key={row.itemId}><h3>{row.code} · {row.description}</h3><dl className="clearance-autofill"><div><dt>Supplier</dt><dd>{row.supplier}</dd></div><div><dt>Truck / driver</dt><dd>{row.truckPlate} · {row.driver}</dd></div><div><dt>DR / PO</dt><dd>{row.dr} / {row.po}</dd></div><div><dt>DR quantity</dt><dd>{row.quantity} {row.uom}</dd></div><div><dt>Supplier lot / SAP batch</dt><dd>{row.lot||'—'} / {row.batch||'—'}</dd></div><div><dt>Gate in</dt><dd>{row.arrival||'—'}</dd></div></dl><div className="form-grid"><label>Mode of delivery<select value={row.mode||''} onChange={event=>change(row.itemId,'mode',event.target.value)}><option value="">Not selected</option><option>PALLETIZED</option><option>MANUAL</option></select></label><label>Disposition<select value={row.disposition||''} onChange={event=>change(row.itemId,'disposition',event.target.value)}><option value="">Not selected</option><option>RELEASE</option><option>HOLD</option><option>REJECT</option></select></label>{fields.map(([key,label])=><label key={key}>{label}<input value={row[key]??''} onChange={event=>change(row.itemId,key,event.target.value)}/></label>)}</div></section>)}{message&&<p role="alert" className="form-error">{message}</p>}<div className="confirmation-footer"><small>Print on A4 landscape at actual size.</small><button className="button primary" disabled={busy||!records.length}>{busy?'Preparing…':'Save & download both copies'}</button></div></form></Dialog>;
}

export function ClearancePage({token,user}:{token:string;user:SessionUser}) {
  const [shipments,setShipments]=useState<Shipment[]>([]),[query,setQuery]=useState(''),[open,setOpen]=useState<Shipment|null>(null),[message,setMessage]=useState('');
  useEffect(()=>{apiRequest<{shipments:Shipment[]}>(token,'/api/clearance','GET').then(result=>setShipments(result.shipments)).catch(error=>setMessage(error.message));},[token]);
  const rows=shipments.filter(row=>`${row.shipmentNumber} ${row.supplier} ${row.truckPlate} ${row.drNumber||''} ${row.items.map(item=>`${item.materialCode} ${item.materialName}`).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const download=async(shipment:Shipment)=>{setMessage('');try{const response=await authenticatedFetch(`/api/shipments/${shipment.id}/clearance.pdf`,{},token);if(!response.ok)throw new Error('Clearance PDF could not be generated');const url=URL.createObjectURL(await response.blob());const anchor=document.createElement('a');anchor.href=url;anchor.download=`inbound-clearance-${shipment.shipmentNumber}.pdf`;anchor.click();URL.revokeObjectURL(url);}catch(error){setMessage(error instanceof Error?error.message:'Unable to download');}};
  return <div className="page-stack clearance-page"><section className="hero-row"><div><span className="eyebrow">Inbound receiving</span><h1>Clearance</h1></div></section><section className="panel clearance-list-panel"><div className="toolbar"><label className="search-box"><span aria-hidden="true">⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search delivery, supplier, truck, DR or material"/></label><span className="count-chip">{rows.length}</span></div>{message&&<div className="sap-message" role="status">{message}</div>}<div className="clearance-entry-list">{rows.map(shipment=><article key={shipment.id}><span><b>{shipment.shipmentNumber}</b><small>{shipment.supplier}</small></span><span><b>{shipment.truckPlate||'No truck'}</b><small>{shipment.scheduledDate} · {shipment.scheduledTime}</small></span><span><b>{shipment.items.map(item=>item.materialCode).join(', ')}</b><small>{shipment.drNumber||'No DR number'}</small></span><div>{user.role!=='sap'&&<button className="button secondary" onClick={()=>setOpen(shipment)}>Open</button>}<button className="button primary" onClick={()=>void download(shipment)}>Download</button></div></article>)}{!rows.length&&<span className="empty-inline">No clearance entries found.</span>}</div></section>{open&&<ClearanceModal shipment={open} token={token} onClose={()=>setOpen(null)}/>}</div>;
}
