"use client";
import { supplierHue } from "./company-colors";
import { useCallback, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { apiRequest, authenticatedFetch } from './api-client';
import { localDate } from './date-utils';
import type { AppData, QuantityAllocation, ReceiptInput, SessionUser, Shipment } from './types';
import type { SupplierResponsePayload } from './dockflow-features';

export function Dialog({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) {
  useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.stopImmediatePropagation(); close(); } }; document.addEventListener('keydown', listener, true); return () => document.removeEventListener('keydown', listener, true); }, [close]);
  return createPortal(<div className="modal-backdrop"><section className="modal receiving-dialog" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="button secondary" onClick={close} type="button">Close</button></div>{children}</section></div>, document.fullscreenElement || document.body);
}
const newTruck = () => ({ truckPlate: '', driverName: '', driverPhone: '', helper1Name: '', helper2Name: '', poNumber: '', drNumber: '', itemIds: [] as number[] });
export function SupplierConfirmation({ shipment, onClose, onSubmit }: { shipment: Shipment; onClose: () => void; onSubmit: (shipment: Shipment, payload: SupplierResponsePayload) => Promise<void> | void }) {
  const [decision,setDecision]=useState<'ACCEPT'|'PROPOSE_ALTERNATIVE'>(shipment.bookingStatus==='PENDING_COMPANY'?'PROPOSE_ALTERNATIVE':'ACCEPT');
  const [changeReason,setChangeReason]=useState(shipment.changeReason || 'Reschedule Time');
  const [reason,setReason]=useState(shipment.supplierResponseReason || '');
  const [date,setDate]=useState(shipment.alternativeDate || shipment.scheduledDate);
  const [time,setTime]=useState(shipment.alternativeTime || shipment.scheduledTime);
  const previous=shipment.confirmedTruckLoads || [];
  const remaining=shipment.items.filter(item=>!previous.some(truck=>truck.itemIds.includes(item.id)));
  const [trucks,setTrucks]=useState(()=>shipment.proposedTrucks?.length ? shipment.proposedTrucks.map(row=>({...newTruck(),...row})) : [{...newTruck(),itemIds:remaining.map(item=>item.id)}]);
  const [allocations,setAllocations]=useState<QuantityAllocation[]>(shipment.quantityAllocations || []);
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const normalizePhone=(value:string)=>{let phone=value.replace(/[\s().-]/g,'');if(/^09\d{9}$/.test(phone))phone='+63'+phone.slice(1);else if(/^9\d{9}$/.test(phone))phone='+63'+phone;else if(/^63\d{10}$/.test(phone))phone='+'+phone;return phone;};
  const editSplit=(index:number,change:Partial<QuantityAllocation>)=>setAllocations(rows=>rows.map((row,i)=>i===index?{...row,...change}:row));
  const settleSplit=(id:number)=>setAllocations(rows=>{const item=shipment.items.find(item=>item.id===id)!;const total=rows.filter(row=>row.itemId===id).reduce((sum,row)=>sum+Number(row.quantity||0),0);const withoutEmpty=rows.filter(row=>row.itemId!==id||row.quantity>0);if(total<item.quantity-0.000001)withoutEmpty.push({itemId:id,quantity:Math.round((item.quantity-total)*1e6)/1e6,date,time});return withoutEmpty;});
  const submit=async(event:React.FormEvent)=>{
    event.preventDefault();if(busy)return;setError('');
    const normalized=trucks.map(row=>({...row,driverPhone:normalizePhone(row.driverPhone),truckPlate:row.truckPlate.trim().toUpperCase()}));
    const assigned=normalized.flatMap(row=>row.itemIds);
    if(assigned.length!==remaining.length||new Set(assigned).size!==assigned.length){setError('Select each material once across the trucks.');return;}
    const invalid=normalized.findIndex(row=>!row.truckPlate||!row.driverName.trim()||!/^\+[1-9]\d{7,14}$/.test(row.driverPhone)||!row.poNumber.trim()||!row.drNumber.trim()||!row.itemIds.length);
    if(invalid>=0){setError(`Truck ${invalid+1}: complete plate, driver, phone, PO, DR and the material checklist. Philippine 09… numbers are accepted.`);return;}
    if(decision==='PROPOSE_ALTERNATIVE'&&changeReason==='Change in quantities'&&shipment.items.some(item=>Math.abs(allocations.filter(row=>row.itemId===item.id).reduce((sum,row)=>sum+row.quantity,0)-item.quantity)>0.000001)){setError('Each material must total its original quantity.');return;}
    setBusy(true);try{await onSubmit(shipment,{decision,changeReason,reason,alternativeDate:date,alternativeTime:time,quantityAllocations:decision==='PROPOSE_ALTERNATIVE'&&changeReason==='Change in quantities'?allocations.filter(row=>row.quantity>0):undefined,loadConfirmed:true,trucks:normalized});onClose();}catch(error){setError(error instanceof Error?error.message:'Unable to confirm');}finally{setBusy(false);}
  };
  return <Dialog title="Confirm delivery" close={onClose}><form className="receiving-form supplier-confirm-form" onSubmit={submit}>
    <div className="confirmation-context"><span className="supplier-dot" style={{background:`hsl(${supplierHue(shipment.supplierId,shipment.supplier)} 65% 48%)`}}/><b>{shipment.supplier}</b><span>{shipment.scheduledDate} · {shipment.scheduledTime}</span><small>{shipment.items.length} material codes</small></div>
    {!previous.length&&<div className="view-toggle response-choice"><button type="button" className={decision==='ACCEPT'?'active':''} onClick={()=>setDecision('ACCEPT')}>Accept proposed time</button><button type="button" className={decision==='PROPOSE_ALTERNATIVE'?'active':''} onClick={()=>setDecision('PROPOSE_ALTERNATIVE')}>Propose alternative</button></div>}
    {decision==='PROPOSE_ALTERNATIVE'&&<section className="alternative-fields"><div className="form-grid"><label>Change requested<select value={changeReason} onChange={event=>{setChangeReason(event.target.value);if(event.target.value==='Change in quantities'&&!allocations.length)setAllocations(shipment.items.map(item=>({itemId:item.id,quantity:item.quantity,date,time})));}}>{['Reschedule Time','Reschedule Date','Change in quantities','Others'].map(value=><option key={value}>{value}</option>)}</select></label><label>Reason / notes<input value={reason} onChange={event=>setReason(event.target.value)} placeholder="Optional details for the planner"/></label><label>Proposed date<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label>Proposed time<input type="time" value={time} onChange={event=>setTime(event.target.value)}/></label></div>
    {changeReason==='Change in quantities'&&shipment.items.map(item=><section className="split-material" key={item.id}><header><b>{item.materialCode}</b><span>Total {item.quantity} {item.uom}</span></header>{allocations.map((row,index)=>row.itemId===item.id&&<div className="split-row" key={index}><label>Quantity<input type="number" min="0" step="any" value={row.quantity||''} onChange={event=>editSplit(index,{quantity:Number(event.target.value)})} onBlur={()=>settleSplit(item.id)}/></label><label>Date<input type="date" value={row.date} onChange={event=>editSplit(index,{date:event.target.value})}/></label><label>Time<input type="time" value={row.time} onChange={event=>editSplit(index,{time:event.target.value})}/></label><button type="button" className="icon-button" aria-label="Remove allocation" onClick={()=>setAllocations(allocations.filter((_,i)=>i!==index))}>×</button></div>)}</section>)}</section>}
    <div className="confirmation-truck-heading"><h3>Truck & material assignment</h3><label>Trucks<select value={trucks.length} onChange={event=>setTrucks(Number(event.target.value)===1?[{...trucks[0],itemIds:remaining.map(item=>item.id)}]:[trucks[0],newTruck()])}><option value="1">1 truck</option>{!previous.length&&<option value="2">2 trucks</option>}</select></label></div>
    <div className="truck-confirm-grid">{trucks.map((truck,index)=><section className="truck-confirm-card" key={index}><header><span className="truck-number">{index+1}</span><b>Truck {index+1}</b><small>{truck.itemIds.length} codes selected</small></header><div className="form-grid">{([['truckPlate','Plate number'],['driverName','Driver name'],['driverPhone','Driver phone'],['poNumber','PO number'],['drNumber','DR number'],['helper1Name','Helper 1 (optional)'],['helper2Name','Helper 2 (optional)']] as const).map(([key,label])=><label key={key}>{label}<input value={truck[key]} placeholder={key==='driverPhone'?'09xxxxxxxxx or +63…':label} onChange={event=>setTrucks(trucks.map((row,i)=>i===index?{...row,[key]:event.target.value}:row))}/></label>)}</div><div className="material-checklist"><header><b>Material checklist</b><small>Select codes carried by this truck</small></header>{remaining.map(item=><label className="material-check" key={item.id}><input type="checkbox" checked={truck.itemIds.includes(item.id)} disabled={trucks.some((other,i)=>i!==index&&other.itemIds.includes(item.id))} onChange={event=>setTrucks(trucks.map((row,i)=>i===index?{...row,itemIds:event.target.checked?[...row.itemIds,item.id]:row.itemIds.filter(id=>id!==item.id)}:row))}/><b>{item.materialCode}</b><span>{item.quantity} {item.uom}</span></label>)}</div></section>)}</div>
    <div className="confirmation-footer">{error?<p className="form-error" role="alert">{error}</p>:<small>{decision==='PROPOSE_ALTERNATIVE'?'Planner approval will book these trucks and create their QR codes.':'Review the truck details and selected materials.'}</small>}<button className="button primary" disabled={busy}>{busy?'Saving…':decision==='ACCEPT'?'Confirm delivery':'Send for planner approval'}</button></div>
  </form></Dialog>;
}

export function ReceiptModal({ shipment, onClose, onSubmit }: { shipment: Shipment; onClose: () => void; onSubmit: (receipt: ReceiptInput) => Promise<void> }) {
 const [outcome,setOutcome]=useState<'FULL'|'NOT_OTIF'>('FULL'),[issue,setIssue]=useState('');
 const [items,setItems]=useState(shipment.items.map(item=>({itemId:item.id,rejectedQuantity:0,reason:'',date:'',time:''})));
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog title="Receive delivery" close={onClose}><form className="receiving-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{await onSubmit({outcome,reason:issue,items:items.map(row=>({...row,acceptedQuantity:shipment.items.find(item=>item.id===row.itemId)!.quantity-(outcome==='FULL'?0:row.rejectedQuantity)}))});onClose();}catch(error){setError(error instanceof Error?error.message:'Unable to record receiving');}finally{setBusy(false);}}}><div className="confirmation-context"><b>{shipment.supplier}</b><span>{shipment.truckPlate} · {shipment.shipmentNumber}</span></div><label>Receiving result<select value={outcome} onChange={event=>setOutcome(event.target.value as typeof outcome)}><option value="FULL">OTIF — all items accepted</option><option value="NOT_OTIF">Not OTIF — record the issue</option></select></label><small>Gate-in time determines timeliness. A late delivery remains Not OTIF even when all items are accepted.</small>{outcome==='NOT_OTIF'&&<label>Reason<select value={issue} onChange={event=>setIssue(event.target.value)} required><option value="">Select reason</option>{['Late arrival','Short delivery','Damaged packaging','Quality rejected','Incorrect material','Expired / shelf life','Missing documents','Other'].map(value=><option key={value}>{value}</option>)}</select></label>}{items.map((row,index)=>{const item=shipment.items.find(item=>item.id===row.itemId)!;const patch=(change:Partial<typeof row>)=>setItems(current=>current.map((value,i)=>i===index?{...value,...change}:value));return <section className="allocation-section" key={row.itemId}><b>{item.materialCode} · {item.quantity} {item.uom}</b>{outcome==='NOT_OTIF'&&<><label>Rejected / short quantity ({item.uom})<input type="number" min="0" max={item.quantity} step="any" value={row.rejectedQuantity} onChange={event=>patch({rejectedQuantity:Number(event.target.value)})} required/></label>{row.rejectedQuantity>0&&<div className="form-grid"><label>Rejection details<input value={row.reason} onChange={event=>patch({reason:event.target.value})} placeholder={issue||'Describe the issue'} required/></label><label>Possible replacement date (optional)<input type="date" value={row.date} onChange={event=>patch({date:event.target.value})}/></label><label>Possible replacement time (optional)<input type="time" value={row.time} onChange={event=>patch({time:event.target.value})}/></label><strong>Accepted {item.quantity-row.rejectedQuantity} {item.uom}</strong></div>}</>}</section>;})}{error&&<p role="alert" className="form-error">{error}</p>}<div className="confirmation-footer"><small>The supplier receives the result and any replacement request. The truck can proceed to Gate out.</small><button className="button primary" disabled={busy}>{busy?'Saving…':'Finish receiving'}</button></div></form></Dialog>;
}
type SapRow = { key: string; revision: number; verified: boolean; values: Record<string, string | number> };
export function SapPage({ token }: { token: string }) {
  const [rows,setRows]=useState<SapRow[]>([]),[columns,setColumns]=useState<[string,string,number,string][]>([]),[hidden,setHidden]=useState<string[]>([]),[dirty,setDirty]=useState<string[]>([]);
  const [message,setMessage]=useState(''),[available,setAvailable]=useState(false),[busy,setBusy]=useState(false),[hasMore,setHasMore]=useState(false);
  const sentinel=useRef<HTMLDivElement>(null),loading=useRef(false),offset=useRef(0),dirtyRef=useRef<string[]>([]),rowsRef=useRef<SapRow[]>([]);
  useEffect(()=>{dirtyRef.current=dirty;},[dirty]);
  useEffect(()=>{rowsRef.current=rows;},[rows]);
  const fetchRows=useCallback(async(more=false)=>{
    if(loading.current)return;loading.current=true;
    const start=more?offset.current:0;
    try{const result=await apiRequest<{rows:SapRow[];columns:typeof columns;hasMore:boolean;available:boolean;message?:string}>(token,`/api/sap/rows?offset=${start}`,'GET');setColumns(result.columns);setAvailable(result.available);setMessage(result.message||'');
      if(!result.available){if(!dirtyRef.current.length){setRows([]);offset.current=0;}setHasMore(false);return;}
      const refreshed:SapRow[]=[];
      if(!more) {const older=rowsRef.current.slice(25);for(let i=0;i<older.length;i+=25){const page=await apiRequest<{rows:SapRow[];available:boolean}>(token,`/api/sap/rows?keys=${older.slice(i,i+25).map(row=>row.key).join(',')}`,'GET');if(!page.available){setAvailable(false);setMessage('No data. Reconnect to the SAP network.');return;}refreshed.push(...page.rows);}}
      setRows(current=>{const merged=new Map(current.map(row=>[row.key,row]));for(const row of [...result.rows,...refreshed])if(!dirtyRef.current.includes(row.key))merged.set(row.key,row);return start===0?[...result.rows.map(row=>merged.get(row.key)!),...current.filter(row=>!result.rows.some(incoming=>incoming.key===row.key)).map(row=>merged.get(row.key)!)]:[...merged.values()];});
      if(more||offset.current<=25){offset.current=start+result.rows.length;setHasMore(result.hasMore);}
    }catch(error){setAvailable(false);if(!dirtyRef.current.length){setRows([]);offset.current=0;}setMessage(error instanceof Error?error.message:'No data');}finally{loading.current=false;}
  },[token]);
  useEffect(()=>{void fetchRows();const timer=setInterval(()=>void fetchRows(),2000);return()=>clearInterval(timer);},[fetchRows]);
  useEffect(()=>{if(!sentinel.current)return;const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting&&hasMore)void fetchRows(true);},{rootMargin:'160px'});observer.observe(sentinel.current);return()=>observer.disconnect();},[hasMore,fetchRows,rows.length]);
  const save=async()=>{setBusy(true);setMessage('');try{const result=await apiRequest<{saved:{key:string;revision:number}[]}>(token,'/api/sap/rows','PUT',{rows:rows.filter(row=>dirty.includes(row.key))});setRows(current=>current.map(row=>{const saved=result.saved.find(item=>item.key===row.key);return saved?{...row,revision:saved.revision}:row;}));setDirty([]);dirtyRef.current=[];await fetchRows();}catch(error){setMessage(error instanceof Error?error.message:'Save failed');}finally{setBusy(false);}};
  const change=(key:string,column:string,value:string)=>{dirtyRef.current=[...new Set([...dirtyRef.current,key])];setDirty(dirtyRef.current);setRows(current=>current.map(row=>row.key===key?{...row,values:{...row.values,[column]:value}}:row));};
  return <div className="page-stack sap-page"><div className="hero-row"><div><span className="eyebrow">SAP Analysis</span><h1>Receiving register</h1></div><div className="sap-actions"><span className={`connection-chip ${available?'connected':''}`}>{available?'Connected · refresh 2s':'No data · network unavailable'}</span><button className="button primary" disabled={busy||!dirty.length||!available} onClick={()=>void save()}>Save {dirty.length||''}</button><button className="button secondary" disabled={busy||!!dirty.length||!available} onClick={async()=>{try{const response=await authenticatedFetch('/api/sap/export.xlsx',{},token);if(!response.ok)throw new Error('The workbook is unavailable');const url=URL.createObjectURL(await response.blob());const anchor=document.createElement('a');anchor.href=url;anchor.download='dockflow-sap-receiving.xlsx';anchor.click();URL.revokeObjectURL(url);}catch(error){setMessage(error instanceof Error?error.message:'Download failed');}}}>Download Excel</button></div></div>
    <details className="sap-column-config"><summary>Columns</summary><div className="worksheet-options">{columns.map(([key,label])=><label key={key}><input type="checkbox" checked={!hidden.includes(key)} onChange={event=>setHidden(event.target.checked?hidden.filter(item=>item!==key):[...hidden,key])}/>{label}</label>)}</div></details>
    {message&&<p className="sap-message" role="status">{message}{dirty.length?' Unsaved edits have been kept.':''}</p>}
    <div className="sap-scroll"><table className="sap-table"><colgroup>{columns.filter(([key])=>!hidden.includes(key)).map(([key,,width])=><col key={key} style={{width:width*8}}/>)}</colgroup><thead><tr>{columns.filter(([key])=>!hidden.includes(key)).map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{(available?rows:[]).map(row=><tr key={row.key} className={dirty.includes(row.key)?'edited':''}>{columns.filter(([key])=>!hidden.includes(key)).map(([key,label])=><td key={key} className={key==='batch'?'sap-batch':key==='matdoc'?'sap-matdoc':key==='actualReceived'?'sap-actual':''}><input aria-label={`${label} ${row.key}`} value={row.values[key]??''} readOnly={key==='encodedBy'||!available||busy} onChange={event=>change(row.key,key,event.target.value)}/></td>)}</tr>)}</tbody></table><div ref={sentinel} className="sap-load-more">{hasMore?<button className="text-button" onClick={()=>void fetchRows(true)}>Load 25 more</button>:rows.length?`${rows.length} records loaded`:'No data'}</div></div>
  </div>;
}
export function KpiPanel({ month, onChange }: { month:string; onChange:(month:string)=>void }) {
  return <label className="report-month-filter">Report month<input type="month" value={month} onChange={event=>onChange(event.target.value)}/></label>;
}

type CatalogItem={id:number;ecosystemId:number;materialCode:string;uom:string};
export function EcosystemPage({token,user,refresh}:{token:string;data:AppData;user:SessionUser;refresh:()=>Promise<void>}) {
 const [ecosystems,setEcosystems]=useState<{id:number;name:string}[]>([]),[materials,setMaterials]=useState<CatalogItem[]>([]),[ecosystemId,setEcosystemId]=useState(user.supplierId||0),[selected,setSelected]=useState<Record<number,string>>({});
 const [code,setCode]=useState(''),[uom,setUom]=useState('KG'),[date,setDate]=useState(localDate()),[time,setTime]=useState('09:00'),[area,setArea]=useState(user.workArea==='SAVOURY'?'SAVOURY':'DRESSINGS'),[manage,setManage]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const requestId=useRef('');
 const load=useCallback(async()=>{const result=await apiRequest<{ecosystems:typeof ecosystems;materials:CatalogItem[]}>(token,'/api/ecosystem','GET');setEcosystems(result.ecosystems);setMaterials(result.materials);setEcosystemId(current=>current||result.ecosystems[0]?.id||0);},[token]);
 useEffect(()=>{apiRequest<{ecosystems:{id:number;name:string}[];materials:CatalogItem[]}>(token,'/api/ecosystem','GET').then(result=>{setEcosystems(result.ecosystems);setMaterials(result.materials);setEcosystemId(current=>current||result.ecosystems[0]?.id||0);}).catch(error=>setMessage(error.message));},[token]);
 const act=async(path:string,method:string,body?:unknown)=>{setBusy(true);setMessage('');try{const result=await apiRequest<{notification?:{status:string}}>(token,path,method,body);await load();await refresh();setMessage(result.notification?result.notification.status==='SENT'?'Request sent to Ecosystem.':'Request saved. Email is pending configuration or recipient verification.':'Catalog updated.');return true;}catch(error){setMessage(error instanceof Error?error.message:'Unable to save');return false;}finally{setBusy(false);}};
 const visible=materials.filter(row=>row.ecosystemId===ecosystemId);
 return <div className="page-stack"><div className="hero-row"><div><span className="eyebrow">Third-party warehouse</span><h1>Ecosystem requests</h1></div>{['admin','ecosystem'].includes(user.role)&&<button className="button secondary" onClick={()=>setManage(!manage)}>Manage materials</button>}</div><div className="ecosystem-selector"><label>Receiving warehouse<select value={ecosystemId} onChange={event=>{setEcosystemId(Number(event.target.value));setSelected({});requestId.current='';}}>{ecosystems.map(eco=><option key={eco.id} value={eco.id}>{eco.name}</option>)}</select></label><small>Select material codes and request a delivery to ULI.</small></div>
 {message&&<p role="status" className="sap-message">{message}</p>}
 {manage&&<form className="catalog-add" onSubmit={async event=>{event.preventDefault();if(await act('/api/ecosystem/materials','POST',{ecosystemId,materialCode:code,uom}))setCode('');}}><label>Material code<input value={code} onChange={event=>setCode(event.target.value)} required/></label><label>UOM<input value={uom} onChange={event=>setUom(event.target.value)} required/></label><button className="button primary" disabled={busy||!ecosystemId}>Add material</button></form>}
 <form className="ecosystem-request-layout" onSubmit={async event=>{event.preventDefault();if(!requestId.current)requestId.current=crypto.randomUUID();const success=await act('/api/ecosystem/transfers','POST',{ecosystemId,items:Object.entries(selected).map(([id,quantity])=>({id:Number(id),quantity:Number(quantity)})),date,time,area,requestId:requestId.current});if(success){setSelected({});requestId.current='';}}}>
 <section className="panel catalog-list"><div className="panel-head"><h2>Material checklist</h2><span className="count-chip">{visible.length} codes</span></div>{visible.map(row=><div className="catalog-row" key={row.id}><label><input type="checkbox" checked={row.id in selected} disabled={user.role==='ecosystem'} onChange={event=>setSelected(current=>{const next={...current};if(event.target.checked)next[row.id]='';else delete next[row.id];return next;})}/><b>{row.materialCode}</b><small>{row.uom}</small></label>{row.id in selected&&<input aria-label={`Quantity ${row.materialCode}`} type="number" min="0.000001" step="any" value={selected[row.id]} onChange={event=>setSelected({...selected,[row.id]:event.target.value})} placeholder="Quantity" required/>}{manage&&<button type="button" className="icon-button danger" aria-label={`Remove ${row.materialCode}`} disabled={busy} onClick={()=>void act(`/api/ecosystem/materials/${row.id}`,'DELETE')}>×</button>}</div>)}{!visible.length&&<p className="empty-inline">No requestable materials have been added.</p>}</section>
 {user.role!=='ecosystem'&&<section className="panel request-details"><h3>Delivery request</h3><label>Destination<select value={area} onChange={event=>setArea(event.target.value)}>{(user.role==='planner'?[user.workArea||'DRESSINGS']:['DRESSINGS','SAVOURY']).map(area=><option key={area}>{area}</option>)}</select></label><label>Delivery date<input type="date" value={date} onChange={event=>setDate(event.target.value)} required/></label><label>Entrance time<input type="time" value={time} onChange={event=>setTime(event.target.value)} required/></label><button className="button primary" disabled={busy||!Object.keys(selected).length}>Send request · {Object.keys(selected).length} codes</button></section>}</form></div>;
}
