"use client";
import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { apiRequest, authenticatedFetch } from './api-client';
import { localDate } from './date-utils';
import type { AppData, QuantityAllocation, ReceiptInput, SessionUser, Shipment } from './types';
import type { SupplierResponsePayload } from './dockflow-features';

function Dialog({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) {
  useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.stopImmediatePropagation(); close(); } }; document.addEventListener('keydown', listener, true); return () => document.removeEventListener('keydown', listener, true); }, [close]);
  return createPortal(<div className="modal-backdrop"><section className="modal receiving-dialog" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="button secondary" onClick={close} type="button">Close</button></div>{children}</section></div>, document.fullscreenElement || document.body);
}
const newTruck = () => ({ truckPlate: '', driverName: '', driverPhone: '', helper1Name: '', helper2Name: '', poNumber: '', drNumber: '', itemIds: [] as number[] });
export function SupplierConfirmation({ shipment, onClose, onSubmit }: { shipment: Shipment; onClose: () => void; onSubmit: (shipment: Shipment, payload: SupplierResponsePayload) => Promise<void> | void }) {
  const [decision, setDecision] = useState<'ACCEPT' | 'PROPOSE_ALTERNATIVE'>('ACCEPT');
  const [reason, setReason] = useState('');
  const [date, setDate] = useState(''); const [time, setTime] = useState('');
  const [trucks, setTrucks] = useState([newTruck()]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [allocations, setAllocations] = useState<QuantityAllocation[]>([]);
  const previous = shipment.confirmedTruckLoads || [];
  const remaining = shipment.items.filter(item => !previous.some(truck => truck.itemIds.includes(item.id)));
  const updateSplit = (index: number, change: Partial<QuantityAllocation>) => setAllocations(current => {
    const next = current.map((row, i) => i === index ? { ...row, ...change } : row);
    const item = shipment.items.find(item => item.id === next[index].itemId)!;
    const total = next.filter(row => row.itemId === item.id).reduce((sum, row) => sum + Number(row.quantity || 0), 0);
    if ('quantity' in change && total < item.quantity - 0.000001 && !next.some(row => row.itemId === item.id && !row.quantity)) next.push({ itemId: item.id, quantity: 0, date: date || shipment.scheduledDate, time: time || shipment.scheduledTime });
    return next;
  });
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); if (busy) return; setError('');
    if (decision === 'ACCEPT') {
      const assigned = trucks.flatMap(truck => truck.itemIds);
      if (assigned.length !== remaining.length || new Set(assigned).size !== assigned.length) { setError('Assign every remaining material to one truck.'); return; }
      if (trucks.some(truck => !truck.itemIds.length || !truck.driverName.trim() || !truck.truckPlate.trim() || !/^\+[1-9]\d{7,14}$/.test(truck.driverPhone) || !truck.poNumber.trim() || !truck.drNumber.trim())) { setError('Each truck needs materials, plate, driver, international phone number, PO and DR numbers.'); return; }
    } else if (allocations.length && shipment.items.some(item => Math.abs(allocations.filter(row => row.itemId === item.id).reduce((sum, row) => sum + row.quantity, 0) - item.quantity) > 0.000001 || allocations.some(row => row.quantity <= 0))) { setError('Complete positive quantities that add up to each original material total.'); return; }
    setBusy(true);
    try { await onSubmit(shipment, { decision, reason, alternativeDate: date || undefined, alternativeTime: time || undefined, quantityAllocations: allocations.length ? allocations : undefined, loadConfirmed: true, trucks: decision === 'ACCEPT' ? trucks : [] }); onClose(); } catch (error) { setError(error instanceof Error ? error.message : 'Unable to save'); } finally { setBusy(false); }
  };
  return <Dialog title="Confirm delivery" close={onClose}><form onSubmit={submit} className="receiving-form"><p>{shipment.supplier} · {shipment.scheduledDate} · {shipment.scheduledTime}</p>
    {!previous.length && <div className="view-toggle"><button type="button" className={decision === 'ACCEPT' ? 'active' : ''} onClick={() => setDecision('ACCEPT')}>Accept proposed time</button><button type="button" className={decision === 'PROPOSE_ALTERNATIVE' ? 'active' : ''} onClick={() => setDecision('PROPOSE_ALTERNATIVE')}>Propose alternative</button></div>}
    {decision === 'PROPOSE_ALTERNATIVE' ? <><div className="form-grid"><label>Proposed date (optional)<input type="date" value={date} onChange={event => setDate(event.target.value)} /></label><label>Proposed time (optional)<input type="time" value={time} onChange={event => setTime(event.target.value)} /></label><label>Reason (optional)<textarea value={reason} onChange={event => setReason(event.target.value)} /></label></div><p>Blank fields keep the original schedule. Quantities remain equal to the original order.</p><button type="button" className="button secondary" onClick={() => setAllocations(allocations.length ? [] : shipment.items.map(item => ({ itemId: item.id, quantity: item.quantity, date: date || shipment.scheduledDate, time: time || shipment.scheduledTime })))}>{allocations.length ? 'Keep original quantities' : 'Split proposed quantities'}</button>
      {shipment.items.map(item => allocations.some(row => row.itemId === item.id) && <section className="allocation-section" key={item.id}><b>{item.materialCode} · Required {item.quantity} {item.uom}</b>{allocations.map((row, index) => row.itemId === item.id && <div className="allocation-row" key={index}><label>Quantity<input type="number" min="0" step="any" value={row.quantity || ''} onChange={event => updateSplit(index, { quantity: Number(event.target.value) })} /></label><label>Date<input type="date" value={row.date} onChange={event => updateSplit(index, { date: event.target.value })} /></label><label>Time<input type="time" value={row.time} onChange={event => updateSplit(index, { time: event.target.value })} /></label><button type="button" className="button secondary" onClick={() => setAllocations(allocations.filter((_, i) => i !== index))}>Remove</button></div>)}<small>Allocated: {allocations.filter(row => row.itemId === item.id).reduce((sum, row) => sum + row.quantity, 0)} / {item.quantity} {item.uom}</small></section>)}</> : <>
      <label>Number of trucks<select value={trucks.length} onChange={event => setTrucks(Array.from({ length: Number(event.target.value) }, (_, i) => trucks[i] || newTruck()))}><option value="1">1 truck</option>{!previous.length && <option value="2">2 trucks</option>}</select></label>
      <div className="truck-confirm-grid">{trucks.map((truck, index) => <section key={index} className="allocation-section"><h3>Truck {previous.length + index + 1}</h3><div className="form-grid">{([['truckPlate', 'Plate number'], ['driverName', 'Driver name'], ['driverPhone', 'Driver phone (+63…)'], ['helper1Name', 'Helper 1 (optional)'], ['helper2Name', 'Helper 2 (optional)'], ['poNumber', 'PO number'], ['drNumber', 'DR number']] as const).map(([key, label]) => <label key={key}>{label}<input value={truck[key]} onChange={event => setTrucks(trucks.map((row, i) => i === index ? { ...row, [key]: event.target.value } : row))} /></label>)}</div><h4>Material checklist</h4>{remaining.map(item => <label className="material-check" key={item.id}><input type="checkbox" checked={truck.itemIds.includes(item.id)} disabled={trucks.some((other, i) => i !== index && other.itemIds.includes(item.id))} onChange={event => setTrucks(trucks.map((row, i) => i === index ? { ...row, itemIds: event.target.checked ? [...row.itemIds, item.id] : row.itemIds.filter(id => id !== item.id) } : row))} />{item.materialCode} · {item.quantity} {item.uom}</label>)}</section>)}</div></>}
    {error && <p role="alert" className="form-error">{error}</p>}<div className="modal-actions"><button className="button primary" disabled={busy}>{busy ? 'Saving…' : decision === 'ACCEPT' ? 'Confirm trucks and materials' : 'Send for planner review'}</button></div></form></Dialog>;
}
export function ReceiptModal({ shipment, onClose, onSubmit }: { shipment: Shipment; onClose: () => void; onSubmit: (receipt: ReceiptInput) => Promise<void> }) {
  const [outcome, setOutcome] = useState<'FULL' | 'NOT_IN_FULL'>('FULL');
  const [items, setItems] = useState(shipment.items.map(item => ({ itemId: item.id, acceptedQuantity: item.quantity, reason: '', date: localDate(), time: shipment.scheduledTime })));
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <Dialog title="Receiving inspection" close={onClose}><form className="receiving-form" onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { await onSubmit({ outcome, items: outcome === 'FULL' ? items.map(row => ({ ...row, acceptedQuantity: shipment.items.find(item => item.id === row.itemId)!.quantity })) : items }); onClose(); } catch (error) { setError(error instanceof Error ? error.message : 'Unable to record inspection'); } finally { setBusy(false); } }}><p>{shipment.shipmentNumber} · {shipment.truckPlate}</p><label>Inspection outcome<select value={outcome} onChange={event => setOutcome(event.target.value as typeof outcome)}><option value="FULL">Received — In Full</option><option value="NOT_IN_FULL">Received – Not in Full</option></select></label><small>On-time performance is calculated from Gate in; receiving cannot override it.</small>{items.map((row, index) => { const item = shipment.items.find(item => item.id === row.itemId)!; const patch = (change: Partial<typeof row>) => setItems(items.map((value, i) => i === index ? { ...value, ...change } : value)); return <section className="allocation-section" key={row.itemId}><b>{item.materialCode} · Expected {item.quantity} {item.uom}</b>{outcome === 'NOT_IN_FULL' && <><label>Accepted quantity<input type="number" min="0" max={item.quantity} step="any" value={row.acceptedQuantity} onChange={event => patch({ acceptedQuantity: Number(event.target.value) })} required /></label>{row.acceptedQuantity < item.quantity && <div className="form-grid"><label>Issue<select value={row.reason} onChange={event => patch({ reason: event.target.value })} required><option value="">Choose reason</option>{['Short delivery', 'Damaged packaging', 'Quality rejected', 'Incorrect material', 'Expired / shelf life', 'Missing documents', 'Other'].map(reason => <option key={reason}>{reason}</option>)}</select></label><label>Reason / details<input value={row.reason} onChange={event => patch({ reason: event.target.value })} required /></label><label>Replacement date<input type="date" value={row.date} onChange={event => patch({ date: event.target.value })} required /></label><label>Replacement time<input type="time" value={row.time} onChange={event => patch({ time: event.target.value })} required /></label><strong>Outstanding: {item.quantity - row.acceptedQuantity} {item.uom}</strong></div>}</>}</section>; })}{error && <p role="alert" className="form-error">{error}</p>}<button className="button primary" disabled={busy}>{busy ? 'Saving…' : 'Finish receiving inspection'}</button></form></Dialog>;
}
type SapRow = { key: string; revision: number; verified: boolean; values: Record<string, string | number> };
export function SapPage({ token }: { token: string }) {
  const [rows, setRows] = useState<SapRow[]>([]); const [columns, setColumns] = useState<[string, string, number, string][]>([]); const [hidden, setHidden] = useState<string[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [dirty, setDirty] = useState<string[]>([]);
  useEffect(() => { apiRequest<{ rows: SapRow[]; columns: typeof columns }>(token, '/api/sap/rows', 'GET').then(result => { setRows(result.rows); setColumns(result.columns); }).catch(error => setError(error.message)); }, [token]);
  const save = async () => { setBusy(true); setError(''); try { const result = await apiRequest<{ rows: SapRow[] }>(token, '/api/sap/rows', 'PUT', { rows: rows.filter(row => dirty.includes(row.key)) }); setRows(result.rows); setDirty([]); } catch (error) { setError(error instanceof Error ? error.message : 'Save failed'); } finally { setBusy(false); } };
  const markDirty = (key: string) => setDirty(current => [...new Set([...current, key])]);
  return <div className="page-stack"><div className="hero-row"><div><span className="eyebrow">SAP Analysis</span><h1>Receiving register</h1><p>Trial worksheet · Save records before downloading.</p></div><div className="toolbar"><button className="button primary" disabled={busy || !dirty.length} onClick={() => void save()}>Save {dirty.length || ''}</button><button className="button secondary" disabled={busy || !!dirty.length} onClick={async () => { setError(''); try { const response = await authenticatedFetch('/api/sap/export.xlsx', {}, token); if (!response.ok) throw new Error('Download failed'); const url = URL.createObjectURL(await response.blob()); const a = document.createElement('a'); a.href = url; a.download = 'dockflow-sap-receiving.xlsx'; a.click(); URL.revokeObjectURL(url); } catch (error) { setError(error instanceof Error ? error.message : 'Download failed'); } }}>Download Excel</button></div></div>
    <details className="panel receiving-form"><summary>Configure visible columns</summary><div className="worksheet-options">{columns.map(([key, title]) => <label key={key}><input type="checkbox" checked={!hidden.includes(key)} onChange={event => setHidden(event.target.checked ? hidden.filter(value => value !== key) : [...hidden, key])} />{title}</label>)}</div></details>{error && <p role="alert" className="form-error">{error}</p>}<div className="sap-scroll"><table className="sap-table"><thead><tr><th>VERIFIED</th>{columns.filter(([key]) => !hidden.includes(key)).map(([key, title]) => <th key={key}>{title}</th>)}</tr><tr><th>SAP check</th>{columns.filter(([key]) => !hidden.includes(key)).map(([key, , , hint]) => <th key={key}>{hint}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.key}><td><input aria-label={`Verify ${row.key}`} type="checkbox" checked={row.verified} onChange={event => { markDirty(row.key); setRows(rows.map(value => value.key === row.key ? { ...value, verified: event.target.checked } : value)); }} /></td>{columns.filter(([key]) => !hidden.includes(key)).map(([key, title]) => <td key={key} className={key === 'batch' ? 'sap-batch' : key === 'matdoc' ? 'sap-matdoc' : ''}><input aria-label={`${title} ${row.key}`} value={row.values[key] ?? ''} readOnly={key === 'encodedBy'} onChange={event => { markDirty(row.key); setRows(rows.map(value => value.key === row.key ? { ...value, values: { ...value.values, [key]: event.target.value } } : value)); }} /></td>)}</tr>)}</tbody></table></div>{!rows.length && <p className="panel receiving-form">Deliveries appear after Gate in. Available fields will autofill; missing information stays blank for SAP encoding.</p>}</div>;
}
export function KpiPanel({ token, supplierId = 'ALL' }: { token: string; supplierId?: string }) {
  const [month, setMonth] = useState(localDate().slice(0, 7)); const [report, setReport] = useState<Record<string, number | null>>({}); const [error, setError] = useState('');
  useEffect(() => { let active = true; apiRequest<Record<string, number | null>>(token, `/api/reports/kpi?month=${month}${supplierId !== 'ALL' ? `&supplierId=${supplierId}` : ''}`, 'GET').then(result => { if (active) { setReport(result); setError(''); } }).catch(error => { if (active) setError(error.message); }); return () => { active = false; }; }, [token, month, supplierId]);
  return <section className="panel receiving-form"><div className="hero-row"><h2>Monthly OTIF scorecard</h2><label>Report month<input type="month" value={month} onChange={event => setMonth(event.target.value)} /></label></div>{error ? <p role="alert">{error}</p> : <div className="kpi-strip">{[['onTimePercent', 'On time'], ['inFullPercent', 'In full'], ['otifPercent', 'OTIF'], ['evaluated', 'Inspected'], ['awaitingInspection', 'Awaiting inspection']].map(([key, label]) => <div key={key}><small>{label}</small><strong>{report[key] == null ? '—' : `${report[key]}${key.endsWith('Percent') ? '%' : ''}`}</strong></div>)}</div>}<small>Gate in determines timeliness, using the configured grace period. Inspected original deliveries form the OTIF denominator; replacement trips are excluded. Previous-month reports email verified recipients automatically when SMTP is enabled.</small></section>;
}
type Stock = { sourceShipmentId: number; itemId: number; ecosystemId: number; materialCode: string; uom: string; available: number };
export function EcosystemPage({ token, data, user, refresh }: { token: string; data: AppData; user: SessionUser; refresh: () => Promise<void> }) {
  const [stock, setStock] = useState<Stock[]>([]); const [ecosystems, setEcosystems] = useState<{ id: number; name: string }[]>([]); const [error, setError] = useState(''); const [selected, setSelected] = useState<Stock | null>(null); const [quantity, setQuantity] = useState(''); const [date, setDate] = useState(localDate()); const [time, setTime] = useState('09:00'); const [area, setArea] = useState(user.workArea === 'SAVOURY' ? 'SAVOURY' : 'DRESSINGS'); const [busy, setBusy] = useState(false);
  useEffect(() => { apiRequest<{ inventory: Stock[]; ecosystems: typeof ecosystems }>(token, '/api/ecosystem', 'GET').then(result => { setStock(result.inventory); setEcosystems(result.ecosystems); }).catch(error => setError(error.message)); }, [token, data]);
  const act = async (path: string, method: string, body: unknown) => { if (busy) return; setBusy(true); setError(''); try { await apiRequest(token, path, method, body); await refresh(); setSelected(null); } catch (error) { setError(error instanceof Error ? error.message : 'Unable to save'); } finally { setBusy(false); } };
  return <div className="page-stack"><div className="hero-row"><div><span className="eyebrow">Third-party warehouse</span><h1>Ecosystem stock & transfers</h1></div></div>{error && <p role="alert" className="form-error">{error}</p>}{user.role !== 'ecosystem' && <section className="panel receiving-form"><h2>Route a pending delivery to Ecosystem</h2>{data.shipments.filter(s => s.bookingStatus === 'PENDING_SUPPLIER' && !s.confirmedTruckLoads?.length && !s.destinationEcosystemId).map(s => <div className="allocation-row" key={s.id}><span>{s.shipmentNumber} · {s.supplier}</span><select aria-label={`Destination ${s.shipmentNumber}`} defaultValue="" disabled={busy} onChange={event => void act(`/api/shipments/${s.id}/destination`, 'PATCH', { ecosystemId: Number(event.target.value) })}><option value="" disabled>Choose receiving Ecosystem</option>{ecosystems.map(eco => <option value={eco.id} key={eco.id}>{eco.name}</option>)}</select></div>)}</section>}
    <section className="panel receiving-form"><h2>Accepted stock available to request</h2>{stock.filter(row => row.available > 0).map(row => <div className="allocation-row" key={`${row.sourceShipmentId}:${row.itemId}`}><span>{ecosystems.find(eco => eco.id === row.ecosystemId)?.name} · {row.materialCode}</span><b>{row.available} {row.uom}</b>{user.role !== 'ecosystem' && <button className="button secondary" onClick={() => { setSelected(row); setQuantity(String(row.available)); }}>Request delivery to ULI</button>}</div>)}{!stock.some(row => row.available > 0) && <p>No unreserved accepted stock.</p>}</section>
    {selected && <Dialog title="Request stock from Ecosystem" close={() => setSelected(null)}><form className="receiving-form" onSubmit={event => { event.preventDefault(); void act('/api/ecosystem/transfers', 'POST', { ...selected, quantity: Number(quantity), date, time, area }); }}><b>{selected.materialCode} · Available {selected.available} {selected.uom}</b><div className="form-grid"><label>Quantity<input type="number" min="0.000001" max={selected.available} step="any" value={quantity} onChange={event => setQuantity(event.target.value)} required /></label><label>Receiving area<select value={area} onChange={event => setArea(event.target.value)}>{(user.role === 'planner' ? [user.workArea || 'DRESSINGS'] : ['DRESSINGS', 'SAVOURY']).map(area => <option key={area}>{area}</option>)}</select></label><label>Date<input type="date" value={date} onChange={event => setDate(event.target.value)} required /></label><label>Time<input type="time" value={time} onChange={event => setTime(event.target.value)} required /></label></div><button className="button primary" disabled={busy}>Send transfer request</button></form></Dialog>}</div>;
}
