"use client";
import { supplierHue } from "./company-colors";
import { useCallback, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { apiRequest } from './api-client';
import { localDate } from './date-utils';
import type { AppData, QuantityAllocation, ReceiptInput, SessionUser, Shipment } from './types';
import type { SupplierResponsePayload } from './dockflow-features';

export function Dialog({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) {
  useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.stopImmediatePropagation(); close(); } }; document.addEventListener('keydown', listener, true); return () => document.removeEventListener('keydown', listener, true); }, [close]);
  return createPortal(<div className="modal-backdrop"><section className="modal receiving-dialog" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="button secondary" onClick={close} type="button">Close</button></div>{children}</section></div>, document.fullscreenElement || document.body);
}
type ConfirmationTruck = { truckPlate:string;driverName:string;phonePrefix:string;driverPhone:string;helper1Name:string;helper2Name:string;poNumber:string;drNumber:string;itemIds:number[];itemQuantities:Record<string,string> };
const newTruck = (items:Shipment['items'],full=true):ConfirmationTruck => ({ truckPlate:'',driverName:'',phonePrefix:'+63',driverPhone:'',helper1Name:'',helper2Name:'',poNumber:'',drNumber:'',itemIds:full?items.map(item=>item.id):[],itemQuantities:Object.fromEntries(items.map(item=>[item.id,full?String(item.quantity):'0'])) });
const truckForm = (row:NonNullable<Shipment['proposedTrucks']>[number],items:Shipment['items']):ConfirmationTruck => {
  const raw=String(row.driverPhone||'');const digits=raw.replace(/\D/g,'');const local=digits.startsWith('63')?digits.slice(2):digits.startsWith('0')?digits.slice(1):digits;
  return {...newTruck(items,false),...row,phonePrefix:digits.startsWith('0')?'0':'+63',driverPhone:local.slice(0,10),itemQuantities:Object.fromEntries(items.map(item=>[item.id,String(row.itemQuantities?.find(value=>Number(value.itemId)===item.id)?.quantity??(row.itemIds.includes(item.id)?item.quantity:0))]))};
};
export function SupplierConfirmation({ shipment, onClose, onSubmit }: { shipment: Shipment; onClose: () => void; onSubmit: (shipment: Shipment, payload: SupplierResponsePayload) => Promise<void> | void }) {
  const [decision,setDecision]=useState<'ACCEPT'|'PROPOSE_ALTERNATIVE'>(shipment.bookingStatus==='PENDING_COMPANY'?'PROPOSE_ALTERNATIVE':'ACCEPT');
  const [changeReason,setChangeReason]=useState(shipment.changeReason==='Change in quantities'?'Change in quantities':shipment.changeReason==='Others'?'Other':'Reschedule Time and Date');
  const [reason,setReason]=useState(shipment.supplierResponseReason || '');
  const [date,setDate]=useState(shipment.alternativeDate || shipment.scheduledDate);
  const [time,setTime]=useState(shipment.alternativeTime || shipment.scheduledTime);
  const previous=shipment.confirmedTruckLoads || [];
  const remaining=shipment.items.filter(item=>!previous.some(truck=>truck.itemIds.includes(item.id)));
  const [trucks,setTrucks]=useState<ConfirmationTruck[]>(()=>shipment.proposedTrucks?.length ? shipment.proposedTrucks.map(row=>truckForm(row,remaining)) : [newTruck(remaining)]);
  const [allocations,setAllocations]=useState<QuantityAllocation[]>(shipment.quantityAllocations || []);
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const normalizePhone=(prefix:string,value:string)=>{const digits=value.replace(/\D/g,'').slice(0,10);return prefix==='+63'?`+63${digits}`:`0${digits}`;};
  const cleanPlate=(value:string)=>{const raw=value.toUpperCase().replace(/[^A-Z0-9]/g,'');let letters='',numbers='';for(const character of raw){if(letters.length<3){if(/[A-Z]/.test(character))letters+=character;continue;}if(/\d/.test(character)&&numbers.length<4)numbers+=character;}return numbers?`${letters}-${numbers}`:letters;};
  const editSplit=(index:number,change:Partial<QuantityAllocation>)=>setAllocations(rows=>rows.map((row,i)=>i===index?{...row,...change}:row));
  const settleSplit=(id:number)=>setAllocations(rows=>{const item=shipment.items.find(item=>item.id===id)!;const total=rows.filter(row=>row.itemId===id).reduce((sum,row)=>sum+Number(row.quantity||0),0);const withoutEmpty=rows.filter(row=>row.itemId!==id||row.quantity>0);if(total<item.quantity-0.000001)withoutEmpty.push({itemId:id,quantity:Math.round((item.quantity-total)*1e6)/1e6,date,time,cannotDeliver:false,reason:''});return withoutEmpty;});
  const changeTruckCount=(count:number)=>setTrucks(count===1?[{...trucks[0],itemIds:remaining.map(item=>item.id),itemQuantities:Object.fromEntries(remaining.map(item=>[item.id,String(item.quantity)]))}]:[{...trucks[0],itemIds:remaining.map(item=>item.id),itemQuantities:Object.fromEntries(remaining.map(item=>[item.id,String(item.quantity)]))},newTruck(remaining,false)]);
  const setTruckQuantity=(truckIndex:number,itemId:number,raw:string)=>setTrucks(current=>{
    const item=remaining.find(row=>row.id===itemId)!;const amount=raw===''?'':Math.max(0,Math.min(item.quantity,Number(raw)||0));const next=current.map(row=>({...row,itemQuantities:{...row.itemQuantities}}));
    next[truckIndex].itemQuantities[String(itemId)]=String(amount);if(next.length===2)next[1-truckIndex].itemQuantities[String(itemId)]=String(Math.round((item.quantity-Number(amount||0))*1e6)/1e6);
    next.forEach(row=>{row.itemIds=remaining.filter(item=>Number(row.itemQuantities[String(item.id)]||0)>0).map(item=>item.id);});return next;
  });
  const submit=async(event:React.FormEvent)=>{
    event.preventDefault();if(busy)return;setError('');
    const normalized=trucks.map(row=>({...row,driverPhone:normalizePhone(row.phonePrefix,row.driverPhone),truckPlate:cleanPlate(row.truckPlate),itemQuantities:remaining.map(item=>({itemId:item.id,quantity:Number(row.itemQuantities[String(item.id)]||0)})).filter(item=>item.quantity>0)}));
    if(decision==='ACCEPT'){
      const invalidTotal=remaining.find(item=>Math.abs(normalized.reduce((sum,row)=>sum+Number(row.itemQuantities.find(value=>value.itemId===item.id)?.quantity||0),0)-item.quantity)>0.000001);
      if(invalidTotal){setError(`${invalidTotal.materialCode}: truck quantities must total ${invalidTotal.quantity} ${invalidTotal.uom}.`);return;}
      const invalidPlate=normalized.findIndex(row=>!/^[A-Z]{3}-\d{4}$/.test(row.truckPlate));
      if(invalidPlate>=0){setError(`Entry ${invalidPlate+1}: use AAA-1111 — 3 letters, then 4 numbers.`);return;}
      const invalid=normalized.findIndex(row=>!row.driverName.trim()||!/^\+639\d{9}$/.test(row.driverPhone.replace(/^0/,'+63'))||!row.poNumber.trim()||!row.drNumber.trim()||!row.itemIds.length);
      if(invalid>=0){const row=normalized[invalid];const missing=[!row.driverName.trim()&&'driver',!/^\+639\d{9}$/.test(row.driverPhone.replace(/^0/,'+63'))&&'10-digit Philippine phone',!row.poNumber.trim()&&'PO',!row.drNumber.trim()&&'DR',!row.itemIds.length&&'quantity'].filter(Boolean);setError(`Entry ${invalid+1}: check ${missing.join(', ')}.`);return;}
    }
    if(decision==='PROPOSE_ALTERNATIVE'&&changeReason==='Reschedule Time and Date'&&(!date||!time)){setError('Choose the proposed date and time.');return;}
    if(decision==='PROPOSE_ALTERNATIVE'&&changeReason==='Change in quantities'){
      if(shipment.items.some(item=>Math.abs(allocations.filter(row=>row.itemId===item.id).reduce((sum,row)=>sum+Number(row.quantity||0),0)-item.quantity)>0.000001)){setError('Each material must total its original quantity.');return;}
      if(allocations.some(row=>row.cannotDeliver&&!row.reason?.trim())){setError('Add a reason for every quantity that cannot be delivered.');return;}
    }
    setBusy(true);try{await onSubmit(shipment,{decision,changeReason,reason,alternativeDate:date,alternativeTime:time,quantityAllocations:decision==='PROPOSE_ALTERNATIVE'&&changeReason==='Change in quantities'?allocations.filter(row=>row.quantity>0):undefined,loadConfirmed:decision==='ACCEPT',trucks:decision==='ACCEPT'?normalized:undefined});onClose();}catch(error){setError(error instanceof Error?error.message:'Unable to confirm');}finally{setBusy(false);}
  };
  return <Dialog title="Confirm delivery" close={onClose}><form className="receiving-form supplier-confirm-form" onSubmit={submit}>
    <div className="confirmation-context"><div className="confirmation-identity"><span className="supplier-dot" style={{background:`hsl(${supplierHue(shipment.supplierId,shipment.supplier)} 65% 48%)`}}/><span><b>{shipment.supplier}</b><small>{shipment.scheduledDate} · {shipment.scheduledTime}</small></span></div>{!previous.length&&<div className="confirmation-context-actions">{decision==='ACCEPT'&&<div className="truck-count-toggle" aria-label="Number of trucks"><button type="button" className={trucks.length===1?'active':''} onClick={()=>changeTruckCount(1)}>1 truck</button><button type="button" className={trucks.length===2?'active':''} onClick={()=>changeTruckCount(2)}>2 trucks</button></div>}<div className="view-toggle response-choice"><button type="button" className={decision==='ACCEPT'?'active':''} onClick={()=>setDecision('ACCEPT')}>Accept delivery</button><button type="button" className={decision==='PROPOSE_ALTERNATIVE'?'active':''} onClick={()=>setDecision('PROPOSE_ALTERNATIVE')}>Propose alternative</button></div></div>}</div>
    {decision==='PROPOSE_ALTERNATIVE'&&<section className="alternative-fields"><div className="alternative-reason-row"><label>Reason for rescheduling<select value={changeReason} onChange={event=>{setChangeReason(event.target.value);if(event.target.value==='Change in quantities'&&!allocations.length)setAllocations(shipment.items.map(item=>({itemId:item.id,quantity:item.quantity,date,time,cannotDeliver:false,reason:''})));}}>{['Reschedule Time and Date','Change in quantities','Other'].map(value=><option key={value}>{value}</option>)}</select></label>{changeReason!=='Change in quantities'&&<><label>Proposed date<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label>Proposed time<input type="time" value={time} onChange={event=>setTime(event.target.value)}/></label><label>Reason (optional)<input value={reason} onChange={event=>setReason(event.target.value)}/></label></>}</div>
    {changeReason==='Change in quantities'&&shipment.items.map(item=><section className="split-material" key={item.id}><header><b>{item.materialCode}</b><span>{item.quantity} {item.uom}</span></header>{allocations.map((row,index)=>row.itemId===item.id&&<div className={`split-row ${row.cannotDeliver?'cannot-deliver':''}`} key={index}><label>Quantity<input type="number" min="0" step="any" value={row.quantity||''} onChange={event=>editSplit(index,{quantity:Number(event.target.value)})} onBlur={()=>settleSplit(item.id)}/></label>{row.cannotDeliver?<label className="split-reason">Reason<input value={row.reason||''} onChange={event=>editSplit(index,{reason:event.target.value})} required/></label>:<><label>Date<input type="date" value={row.date} onChange={event=>editSplit(index,{date:event.target.value})}/></label><label>Time<input type="time" value={row.time} onChange={event=>editSplit(index,{time:event.target.value})}/></label></>}<button type="button" className={`button compact ${row.cannotDeliver?'secondary':'danger-ghost'}`} onClick={()=>editSplit(index,row.cannotDeliver?{cannotDeliver:false,date:date||shipment.scheduledDate,time:time||shipment.scheduledTime,reason:''}:{cannotDeliver:true,date:'',time:'',reason:''})}>{row.cannotDeliver?'Choose date':"Can't deliver"}</button><button type="button" className="icon-button" aria-label="Remove allocation" onClick={()=>setAllocations(allocations.filter((_,i)=>i!==index))}>×</button></div>)}</section>)}</section>}
    {decision==='ACCEPT'&&<div className="truck-confirm-grid">{trucks.map((truck,index)=><section className="truck-confirm-card" key={index}><header><span className="truck-number">{index+1}</span><b>Truck {index+1}</b></header><div className="truck-detail-lines"><div className="truck-line three"><label>Plate number<input value={truck.truckPlate} maxLength={8} placeholder="AAA-1111" onChange={event=>setTrucks(trucks.map((row,i)=>i===index?{...row,truckPlate:cleanPlate(event.target.value)}:row))}/></label><label>Driver name<input value={truck.driverName} onChange={event=>setTrucks(trucks.map((row,i)=>i===index?{...row,driverName:event.target.value}:row))}/></label><label>Driver&apos;s number<span className="phone-input-combo"><select aria-label="Phone prefix" value={truck.phonePrefix} onChange={event=>setTrucks(trucks.map((row,i)=>i===index?{...row,phonePrefix:event.target.value}:row))}><option value="+63">+63</option><option value="0">0</option></select><input inputMode="numeric" pattern="9[0-9]{9}" maxLength={10} placeholder="9171234567" value={truck.driverPhone} onChange={event=>setTrucks(trucks.map((row,i)=>i===index?{...row,driverPhone:event.target.value.replace(/\D/g,'').slice(0,10)}:row))}/></span></label></div><div className="truck-line"><label>PO number<input value={truck.poNumber} onChange={event=>setTrucks(trucks.map((row,i)=>i===index?{...row,poNumber:event.target.value}:row))}/></label><label>DR number<input value={truck.drNumber} onChange={event=>setTrucks(trucks.map((row,i)=>i===index?{...row,drNumber:event.target.value}:row))}/></label></div><div className="truck-line"><label>Helper 1<input value={truck.helper1Name} onChange={event=>setTrucks(trucks.map((row,i)=>i===index?{...row,helper1Name:event.target.value}:row))}/></label><label>Helper 2<input value={truck.helper2Name} onChange={event=>setTrucks(trucks.map((row,i)=>i===index?{...row,helper2Name:event.target.value}:row))}/></label></div></div><div className="truck-quantity-list"><b>Material quantities</b>{remaining.map(item=><label key={item.id}><span><b>{item.materialCode}</b><small>Total {item.quantity} {item.uom}</small></span><input aria-label={`${item.materialCode} quantity for truck ${index+1}`} type="number" min="0" max={item.quantity} step="any" value={truck.itemQuantities[String(item.id)]??'0'} onChange={event=>setTruckQuantity(index,item.id,event.target.value)}/><em>{item.uom}</em></label>)}</div></section>)}</div>}
    <div className="confirmation-footer">{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Saving…':decision==='ACCEPT'?'Confirm delivery':'Send for approval'}</button></div>
  </form></Dialog>;
}

export function ReceiptModal({ shipment, onClose, onSubmit }: { shipment: Shipment; onClose: () => void; onSubmit: (receipt: ReceiptInput) => Promise<void> }) {
 const [outcome,setOutcome]=useState<'FULL'|'NOT_OTIF'>('FULL'),[issue,setIssue]=useState(''),[otherIssue,setOtherIssue]=useState('');
 const [items,setItems]=useState(shipment.items.map(item=>({itemId:item.id,rejectedQuantity:'0',date:'',time:''})));
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(busy)return;setError('');const reason=issue==='Other'?otherIssue.trim():issue;if(outcome==='NOT_OTIF'&&!reason){setError(issue==='Other'?'Describe the other rejection reason.':'Choose the rejection details.');return;}if(outcome==='NOT_OTIF'&&items.some(row=>row.rejectedQuantity==='')){setError('Enter the rejected / short quantity for every material. Use 0 when none was rejected.');return;}const invalid=items.find(row=>{const item=shipment.items.find(item=>item.id===row.itemId)!;const amount=Number(row.rejectedQuantity);return!Number.isFinite(amount)||amount<0||amount>item.quantity;});if(invalid){setError('Rejected / short quantities must be between 0 and the expected amount.');return;}const missingFollowUp=outcome==='NOT_OTIF'&&items.find(row=>Number(row.rejectedQuantity)>0&&(!row.date||!row.time));if(missingFollowUp){const item=shipment.items.find(item=>item.id===missingFollowUp.itemId)!;setError(`Choose the Follow up date and time for ${item.materialCode}.`);return;}setBusy(true);try{await onSubmit({outcome,reason,items:items.map(row=>{const item=shipment.items.find(item=>item.id===row.itemId)!;const rejected=outcome==='FULL'?0:Number(row.rejectedQuantity);return{itemId:row.itemId,acceptedQuantity:item.quantity-rejected,reason:rejected?reason:'',date:rejected?row.date:'',time:rejected?row.time:''};})});onClose();}catch(error){setError(error instanceof Error?error.message:'Unable to record receiving');}finally{setBusy(false);}};
 return <Dialog title="Receive delivery" close={onClose}><form className="receiving-form receipt-form" onSubmit={submit}><div className="confirmation-context"><b>{shipment.supplier}</b><span>{shipment.truckPlate} · {shipment.shipmentNumber}</span></div><label className="receipt-result">Receiving result<select value={outcome} onChange={event=>setOutcome(event.target.value as typeof outcome)}><option value="FULL">OTIF — all items accepted</option><option value="NOT_OTIF">Not OTIF — record the issue</option></select></label><div className="receipt-items">{items.map((row,index)=>{const item=shipment.items.find(item=>item.id===row.itemId)!;const rejected=row.rejectedQuantity===''?null:Number(row.rejectedQuantity);const accepted=rejected===null?'—':Math.max(0,item.quantity-(outcome==='FULL'?0:rejected));const patch=(change:Partial<typeof row>)=>setItems(current=>current.map((value,i)=>i===index?{...value,...change}:value));return <section className="receipt-item" key={row.itemId}><div className="receipt-material"><small>Material</small><b>{item.materialCode}</b><span>{item.quantity} {item.uom} expected</span></div>{outcome==='NOT_OTIF'&&<><label>Rejected / short ({item.uom})<input type="number" min="0" max={item.quantity} step="any" value={row.rejectedQuantity} onChange={event=>patch({rejectedQuantity:event.target.value})}/></label><label>Follow up date<input type="date" value={row.date} onChange={event=>patch({date:event.target.value})}/></label><label>Follow up time<input type="time" value={row.time} onChange={event=>patch({time:event.target.value})}/></label></>}<div className="receipt-accepted"><small>Accepted amount</small><b>{accepted} {item.uom}</b></div></section>;})}</div>{outcome==='NOT_OTIF'&&<section className="receipt-rejection-details"><label>Rejection details<select value={issue} onChange={event=>setIssue(event.target.value)}><option value="">Select reason</option>{['Late arrival','Short delivery','Damaged packaging','Quality rejected','Incorrect material','Expired / shelf life','Missing documents','Other'].map(value=><option key={value}>{value}</option>)}</select></label>{issue==='Other'&&<label>Describe the issue<input value={otherIssue} onChange={event=>setOtherIssue(event.target.value)} placeholder="Write the rejection reason"/></label>}</section>}{error&&<p role="alert" className="form-error">{error}</p>}<div className="confirmation-footer"><button className="button primary" disabled={busy}>{busy?'Saving…':'Finish receiving'}</button></div></form></Dialog>;
}
type CatalogItem={id:number;ecosystemId:number;materialCode:string;description:string;uom:string};
export function EcosystemPage({token,user,refresh}:{token:string;data:AppData;user:SessionUser;refresh:()=>Promise<void>}) {
 const [ecosystems,setEcosystems]=useState<{id:number;name:string}[]>([]),[materials,setMaterials]=useState<CatalogItem[]>([]),[ecosystemId,setEcosystemId]=useState(user.supplierId||0),[selected,setSelected]=useState<Record<number,string>>({});
 const [code,setCode]=useState(''),[description,setDescription]=useState(''),[uom,setUom]=useState('KG'),[date,setDate]=useState(localDate()),[time,setTime]=useState('09:00'),[area,setArea]=useState(user.workArea==='SAVOURY'?'SAVOURY':'DRESSINGS'),[manage,setManage]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const requestId=useRef('');
 const load=useCallback(async()=>{const result=await apiRequest<{ecosystems:typeof ecosystems;materials:CatalogItem[]}>(token,'/api/ecosystem','GET');setEcosystems(result.ecosystems);setMaterials(result.materials);setEcosystemId(current=>current||result.ecosystems[0]?.id||0);},[token]);
 useEffect(()=>{apiRequest<{ecosystems:{id:number;name:string}[];materials:CatalogItem[]}>(token,'/api/ecosystem','GET').then(result=>{setEcosystems(result.ecosystems);setMaterials(result.materials);setEcosystemId(current=>current||result.ecosystems[0]?.id||0);}).catch(error=>setMessage(error.message));},[token]);
 useEffect(()=>{if(!message)return;const timer=window.setTimeout(()=>setMessage(''),3500);return()=>window.clearTimeout(timer);},[message]);
 const act=async(path:string,method:string,body?:unknown)=>{setBusy(true);setMessage('');try{const result=await apiRequest<{notification?:{status:string}}>(token,path,method,body);await load();await refresh();setMessage(result.notification?result.notification.status==='SENT'?'Request sent to Ecosystem.':'Request saved. Email is pending configuration or recipient verification.':'Catalog updated.');return true;}catch(error){setMessage(error instanceof Error?error.message:'Unable to save');return false;}finally{setBusy(false);}};
 const visible=materials.filter(row=>row.ecosystemId===ecosystemId);
 return <div className="page-stack"><div className="hero-row"><div><span className="eyebrow">Third-party warehouse</span><h1>Ecosystem requests</h1></div><div className="ecosystem-hero-actions"><label className="ecosystem-selector"><span>Receiving warehouse</span><select value={ecosystemId} onChange={event=>{setEcosystemId(Number(event.target.value));setSelected({});requestId.current='';}}>{ecosystems.map(eco=><option key={eco.id} value={eco.id}>{eco.name}</option>)}</select></label>{['admin','ecosystem'].includes(user.role)&&<button className="button secondary" onClick={()=>setManage(true)}>Manage materials</button>}</div></div>
 {message&&<div role="status" className={`ecosystem-toast ${/updated|sent|saved/i.test(message)?'success':'error'}`}>{message}</div>}
 {manage&&<Dialog title="Manage materials" close={()=>setManage(false)}><form className="catalog-add popup" onSubmit={async event=>{event.preventDefault();if(await act('/api/ecosystem/materials','POST',{ecosystemId,materialCode:code,description,uom})){setCode('');setDescription('');}}}><label>Material code<input value={code} onChange={event=>setCode(event.target.value)} required/></label><label>Description<input value={description} onChange={event=>setDescription(event.target.value)} required/></label><label>UOM<input value={uom} onChange={event=>setUom(event.target.value)} required/></label><button className="button primary" disabled={busy||!ecosystemId}>Add material</button></form><div className="catalog-manage-list">{visible.map(row=><div key={row.id}><b>{row.materialCode}</b><span>{row.description||'No description'}</span><small>{row.uom}</small><button type="button" className="icon-button danger" aria-label={`Remove ${row.materialCode}`} disabled={busy} onClick={()=>void act(`/api/ecosystem/materials/${row.id}`,'DELETE')}>×</button></div>)}</div></Dialog>}
 <form className="ecosystem-request-layout" onSubmit={async event=>{event.preventDefault();if(!requestId.current)requestId.current=crypto.randomUUID();const success=await act('/api/ecosystem/transfers','POST',{ecosystemId,items:Object.entries(selected).map(([id,quantity])=>({id:Number(id),quantity:Number(quantity)})),date,time,area,requestId:requestId.current});if(success){setSelected({});requestId.current='';}}}>
 <section className="panel catalog-list"><div className="panel-head"><h2>Material checklist</h2><span className="count-chip">{visible.length} codes</span></div><div className="catalog-grid">{visible.map(row=><div className="catalog-row" key={row.id}><label><input type="checkbox" checked={row.id in selected} disabled={user.role==='ecosystem'} onChange={event=>setSelected(current=>{const next={...current};if(event.target.checked)next[row.id]='';else delete next[row.id];return next;})}/><span className="catalog-material"><b>{row.materialCode}</b><small>{row.description||'No description'} · {row.uom}</small></span></label>{row.id in selected&&<input aria-label={`Quantity ${row.materialCode}`} type="number" min="0.000001" step="any" value={selected[row.id]} onChange={event=>setSelected({...selected,[row.id]:event.target.value})} placeholder="Quantity" required/>}</div>)}</div>{!visible.length&&<span className="empty-inline">No requestable materials have been added.</span>}</section>
 {user.role!=='ecosystem'&&<section className="panel request-details"><h3>Delivery request</h3><label>Destination{user.workArea==='DRESSINGS'||user.workArea==='SAVOURY'?<span className="locked-access-area compact"><span><b>{user.workArea==='DRESSINGS'?'Dressings':'Savoury'}</b><small>Locked to your account area</small></span></span>:<select value={area} onChange={event=>setArea(event.target.value)}><option value="DRESSINGS">Dressings</option><option value="SAVOURY">Savoury</option></select>}</label><label>Delivery date<input type="date" value={date} onChange={event=>setDate(event.target.value)} required/></label><label>Entrance time<input type="time" value={time} onChange={event=>setTime(event.target.value)} required/></label><button className="button primary" disabled={busy||!Object.keys(selected).length}>Send request · {Object.keys(selected).length} codes</button></section>}</form></div>;
}
